### ISSUE TITLE
Environment Variable not working 

### ISSUE THREAD

**Issue by Ben-VP** [harlan-zw/nuxt-seo-kit#7]
### Describe the bug

Setting the environment variable to false doesn't work.

I have the staging domain set to false.

<img width="940" alt="CleanShot 2023-01-08 at 22 49 05@2x" src="https://user-images.githubusercontent.com/59267857/211222973-c555ade4-c052-41d3-89f5-6c7c32dbf3e6.png">

Yet when you go to the staging URL you can see it is still set to index.

<img width="615" alt="CleanShot 2023-01-08 at 22 51 14@2x" src="https://user-images.githubusercontent.com/59267857/211223035-405572f9-41bb-48dd-83ee-cd3a010bd601.png">

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 37.98 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.1 - /opt/homebrew/bin/npm
  Browsers:
    Firefox Developer Edition: 109.0
    Safari: 16.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Hey @Ben-VP 

Thanks for the issue. It looks like it wasn't honoring the environment variable when the NODE_ENV was set to `production`.

This should be fixed in 0.4.10.

**Comment by Ben-VP** [comment]
Hey @harlan-zw,

I've updated to 0.4.10 but it still appears to be an issue. I'll DM you the staging site URL.

Cheers

**Comment by harlan-zw** [comment]
Sorry about that, have pushed up 0.4.11 that may have it properly fixed but still testing.
