### ISSUE TITLE
Title does not seem to be correctly displayed anymore after updating to Nuxt 3.7

### ISSUE THREAD

**Issue by stefanobartoletti** [harlan-zw/nuxt-seo-kit#92]
### Describe the bug

In a situation similar to this

```vue
<template>
  <div class="flex min-h-screen flex-col">
    <SeoKit site-name="Site Name" />
    <SiteHeader />
    <slot></slot>
    <SiteFooter />
  </div>
</template>

<script setup>
useSeoMeta({
  title: () => 'Page Title',
  description: () => 'Page Description',
  ogImage: () => '/path/to/image.png',
})
</script>
```

After upgrading to Nuxt 3.7, the meta title does not seem to be correctly retrieved/displayed anymore.

Before the update, it was correctly `Page Title | Site Name`, while now is `| Site Name`.

Seo Kit is updated to the latest version `1.3.10`

Please let me know if you need further details or info :)

### System / Nuxt Info

```Shell
System:
    OS: Linux 6.4 openSUSE Tumbleweed 20230823
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 5.22 GB / 15.03 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 9.7.1 - ~/.nvm/versions/node/v16.17.0/bin/npm
    pnpm: 8.7.1 - ~/.nvm/versions/node/v16.17.0/bin/pnpm
  Browsers:
    Brave Browser: 116.1.57.53
    Chromium: 116.0.5845.96
```

**Comment by DamianGlowala** [comment]
Having the same issue with `nuxt-seo-kit` v1.3.10 and Nuxt 3.6.5 - the title is `null`

**Comment by harlan-zw** [comment]
Hi, can you see if you're using Unhead v1.4. `npm why unhead`, if not can you delete lock file + re-install.

**Comment by DamianGlowala** [comment]
Deleted lockfile, node_modules and installed dependencies again. No luck so far.

`pnpm why unhead`:
```
@nuxt/devtools 0.8.2
├─┬ @nuxt/devtools-kit 0.8.2
│ └─┬ nuxt 3.6.5 peer
│   └─┬ @unhead/vue 1.4.1
│     └── unhead 1.4.1
└─┬ nuxt 3.6.5 peer
  └─┬ @unhead/vue 1.4.1
    └── unhead 1.4.1
@vueuse/nuxt 10.4.1
└─┬ nuxt 3.6.5 peer
  └─┬ @unhead/vue 1.4.1
    └── unhead 1.4.1
nuxt 3.6.5
└─┬ @unhead/vue 1.4.1
  └── unhead 1.4.1
nuxt-seo-kit 1.3.10
├─┬ nuxt-schema-org 2.2.0
│ └─┬ @unhead/schema-org-vue 0.6.0
│   └─┬ @unhead/vue 1.4.1 peer
│     └── unhead 1.4.1
└─┬ nuxt-unhead 1.4.17
  ├─┬ @vueuse/head 1.3.1
  │ └─┬ @unhead/vue 1.4.1
  │   └── unhead 1.4.1
  └── unhead 1.4.1
```

**Comment by harlan-zw** [comment]
Thanks, will investigate further

**Comment by DamianGlowala** [comment]
Apologies for confusion, this is working correctly on Nuxt 3.6.5! :)

**Comment by stefanobartoletti** [comment]
I can confirm that with nuxt `3.6.5` everything works as expected. I start to have this issue only with `3.7`

**Comment by harlan-zw** [comment]
> I can confirm that with nuxt `3.6.5` everything works as expected. I start to have this issue only with `3.7`

Can you confirm that you're upgrading using `npx nuxi upgrade --force` (should delete lock file + node_modules) and the unhead version `npm why unhead`

I've tried replicating with Nuxt 3.7 and Unhead 1.4.1 and it _seems_ to be working.

**Comment by stefanobartoletti** [comment]
Yes, I always upgrade Nuxt with `npx nuxi upgrade --force` because it is the recommended way.

This is my unhead 

```
npm why unhead
unhead@1.4.1
node_modules/unhead
  unhead@"^1.1.26" from nuxt-unhead@1.4.17
  node_modules/nuxt-unhead
    nuxt-unhead@"^1.4.17" from nuxt-seo-kit@1.3.11
    node_modules/nuxt-seo-kit
      nuxt-seo-kit@"^1.3.11" from the root project
  unhead@"1.4.1" from @unhead/vue@1.4.1
  node_modules/@unhead/vue
    @unhead/vue@"^1.3.7" from nuxt@3.7.0
    node_modules/nuxt
      nuxt@"^3.7.0" from the root project
      peer nuxt@"^3.6.5" from @nuxt/devtools@0.8.2
      node_modules/@nuxt/devtools
        dev @nuxt/devtools@"^0.8.2" from the root project
      peer nuxt@"^3.6.5" from @nuxt/devtools-kit@0.8.2
      node_modules/@nuxt/devtools-kit
        @nuxt/devtools-kit@"0.8.2" from @nuxt/devtools@0.8.2
        node_modules/@nuxt/devtools
          dev @nuxt/devtools@"^0.8.2" from the root project
      peer nuxt@"^3.0.0" from @zadigetvoltaire/nuxt-gtm@0.0.13
      node_modules/@zadigetvoltaire/nuxt-gtm
        @zadigetvoltaire/nuxt-gtm@"^0.0.13" from the root project
    peer @unhead/vue@">=1.1.9" from @unhead/schema-org-vue@0.6.0
    node_modules/@unhead/schema-org-vue
      @unhead/schema-org-vue@"^0.6.0" from nuxt-schema-org@2.2.0
      node_modules/nuxt-schema-org
        nuxt-schema-org@"^2.2.0" from nuxt-seo-kit@1.3.11
        node_modules/nuxt-seo-kit
          nuxt-seo-kit@"^1.3.11" from the root project
    @unhead/vue@"^1.3.1" from @vueuse/head@1.3.1
    node_modules/@vueuse/head
      @vueuse/head@"^1.1.26" from nuxt-unhead@1.4.17
      node_modules/nuxt-unhead
        nuxt-unhead@"^1.4.17" from nuxt-seo-kit@1.3.11
        node_modules/nuxt-seo-kit
          nuxt-seo-kit@"^1.3.11" from the root project
```

And the problems is still here :/

Please let me know if I have to provide more info

**Comment by dargmuesli** [comment]
[Here](https://github.com/harlan-zw/nuxt-seo-kit/issues/87#issuecomment-1699975705) is a reproduction for `v2.0.0-beta.24` and nuxt `3.7.0`: https://stackblitz.com/edit/github-dpzmzy-ex5zxf?file=app.vue
I think it's the same issue or very related.

**Comment by harlan-zw** [comment]
Fixed with Unhead 1.5.1 hopefully :pray: 

Thanks for the issue!

**Comment by stefanobartoletti** [comment]
I updated everything, but the problem is still there, at least for me.

Maybe there is something wrong with my specific configuration, but I still have this issue with nuxt `3.7.1`. unhead `1.6.2` and nuxt-seo-kit `1.3.13`

**Comment by stefanobartoletti** [comment]
I solved this by upgrading nuxt-seo-kit to @nuxtseo/module.

It does not really solve the issue per-se, but with the new module the problem is no longer there.

**Comment by harlan-zw** [comment]
Thanks for confirming, will close for now as the v2 is my main focus at the moment.
